### ISSUE TITLE
Bypassing size-field in mesh refinement

### ISSUE THREAD

**Issue by mortezah** [SCOREC/core#112]
Sometimes there is a need to "directly" mark all or some of the edges in the mesh for split operation (i.e., without using a size field).

**Comment by KazemKamran** [comment]
Hmm, you mean we have to? How can we do the marking? do you have any example that I can follow? 

Actually for what I am trying to do it is better if I can mark all edges and say refine, instead of defining a size field. What I am trying to do is to show MFEM guys that we can easily do a uniform refinement. They do this when the mesh is coarse and exactly by marking edges so if I can do the same then great.

**Comment by ibaned** [comment]
https://github.com/SCOREC/core/blob/master/ma/maSize.h#L67

**Comment by mortezah** [comment]
Thanks, Dan. That should do it.

@KazemKamran 
This is how you would setup mesh adapt with the UniformRefiner pointed out by @ibaned:
Instead of ma::configure() use ma::configureUniformRefine() (Look here https://github.com/SCOREC/core/blob/master/ma/maInput.cc#L185 for the arguments).
