### ISSUE TITLE
MeshAdapt fails with step-fields over elements (possibly SolutionTransfer?)

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#124]
I've noticed that when I attempt to adapt a mesh with an element-defined field that MeshAdapt fails with the following error:

```APF FAILED: unimplemented getNodeXi called```

The error comes from https://github.com/SCOREC/core/blob/master/apf/apfShape.cc#L39. 
My best guess is that during SolutionTransfer, `getNodeXi` is called in the `Constant` class, but there's no implementation. Adding an implementation in https://github.com/SCOREC/core/blob/master/apf/apfShape.cc#L910, such as:

```
    void getNodeXi(int, int, Vector3& xi)
    {
      xi = Vector3(0,0,0);
    }
```
seems to resolve the issue. I'm posting this issue as I'm not sure if this was an intentional omission.

Example code that generates the error:
```
  apf::Mesh2* m;
  m = apf::loadMdsMesh(argv[1], argv[2]);

  apf::Field* errorField = apf::createStepField(m,"local_error",apf::SCALAR);
  apf::MeshIterator* it = m->begin(3);
  apf::MeshEntity* ent;
  double count = 0.0;
  while( (ent = m->iterate(it))){
    apf::setScalar(errorField,ent,0,count);
    count = count+1.0;
  }
  ma::Input* in = ma::configureUniformRefine(m);
  ma::validateInput(in);
  ma::adapt(in);
```

**Comment by bgranzow** [comment]
Yes, from a high level this error is because mesh adapt is attempting to perform solution transfer for the field using the AutoSolutionTransfer mechanism, which simply attempts to interpolate the field during mesh adaptation. For step/constant/IP fields there is no mechanism implemented for this interpolation.

If you have very loose requirements on how this element data is transferred during mesh adapt, you could try using the `VoronoiShape` or the `IPFIt` shape.

https://github.com/SCOREC/core/blob/master/apf/apfShape.h#L126
https://github.com/SCOREC/core/blob/master/apf/apfShape.h#L132

If you have strict requirements (like conservation during adapt or something), then you'd probably have to implement your own solution transfer mechanism for the fields.

https://github.com/SCOREC/core/blob/master/ma/maSolutionTransfer.h#L85

**Comment by zhang-alvin** [comment]
Thanks @bgranzow. I'm trying to transfer element-defined fields to a uniformly-refined field and it looks like the `VoronoiShape` will do the job just fine.
