### ISSUE TITLE
Question: Is there a way to sync the underlying MDS for identical meshes created through uniform refinement?

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#126]
I have a situation where I want to compare field values on a coarse mesh (`mesh0`) with field values on a finer mesh (`mesh2`) which is generated through `uniformRefinement` of `mesh0` twice with no shape correction. I can try to make this comparison if I load `mesh0` with the desired field and uniformly refine twice to attain a mesh that is visually identical to `mesh2`. 

The problem is that the underlying ordering of the entities are not necessarily the same depending on how `mesh2` is generated. If `mesh2` was created directly from:
```
in = ma::configureUniformRefine(`mesh0`,2); 
in->shouldFixShape=false
ma::adapt(in)
```
then the above procedure of refining `mesh0` isn't a problem. 

If `mesh2` was generated through two independent refinements with a write to file in between, which reorders the MDS in the process : 
```
in = ma::configureUniformRefine(`mesh0`,1); 
in->shouldFixShape=false
ma::adapt(in)
`mesh1`->writeNative()
in = ma::configureUniformRefine(`mesh1`,1); 
in->shouldFixShape=false
ma::adapt(in)
```
the refining `mesh0` directly isn't going to work.

Is there a way of "syncing" the MDS for two meshes that should be identical but may be generated via different paths?

**Comment by bgranzow** [comment]
Your problem arises because calling `mesh->writeNative('name.smb')` makes a call to reorder the entities.

https://github.com/SCOREC/core/blob/master/mds/mds_smb.c#L755

If you are only calling writeNative to write the mesh and then load it back in to get two separate mesh instances, you could instead use the [createMdsMesh](https://github.com/SCOREC/core/blob/master/mds/apfMDS.h#L73) method, which copies one mesh to another. Then you could perform mesh refinement on the copied mesh instance.

This presupposes the nested mesh ordering doesn't change, though which (1) could be a scary assumption and (2) is probably not too good if you're going to do something like full FEM assembly on the nested mesh.

The most general thing to do would be to maintain some relational information from the nested mesh to the parent mesh via some user-defined [SolutionTransfer](https://github.com/SCOREC/core/blob/master/ma/maSolutionTransfer.h#L27) scheme.

**Comment by KennethEJansen** [comment]
You could also generalize what we have done for mapping between partitioning steps.

That is you could attach the vertex number prior to UR to the mesh.  Obviously new nodes would not have a map but all the original nodes could keep this attached data to create a map back to the original mesh of the solution whenever you needed it.  Obviously if you go to files you have to make sure this attached data is also sent to file and make sure it is attached when read back in.

The final step in this is to then use that map to obtain a solution field on the original mesh and write it in whatever format you need.

This has all been done for PHASTA solution files to bring it back to smaller partitions but it is conceptually the same to bring it back to a pre-UR mesh.

---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by zhang-alvin** [comment]
@bgranzow @KennethEJansen Thanks for the replies. Both are good ideas/perspectives that I will consider.
