### ISSUE TITLE
static_cast or reinterpret_cast

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#141]
I am wondering what is the correct way to cast a Sim-based mesh entity to apf mesh entity (or the other way around)?

I see that "static_cast" is used at many places and "reinterpret_cast" is also used at many other places.
Do we have a rule for this?

Based on this webpage:
https://stackoverflow.com/questions/332030/when-should-static-cast-dynamic-cast-const-cast-and-reinterpret-cast-be-used

"reinterpret_cast" should be used with cautions.

Thank you,
Fan

**Comment by tobinw** [comment]
For all intents and purposes an apf::MeshEntity is an entirely opaque type. 

It isn't actually defined anywhere, it is just a type used for the API. Behind the API we cast to the real type of the entity, whether that be mds_ent or a simmetrix mesh ent or some other mesh entity type. Since we never operate on an apf::MeshEntity directly there is never an issue in casting TO an apf::MeshEntity. 

It is technically possible to cast FROM an apf::MeshEntity to the wrong type. In practice this would be difficult in the current API since it would require having two meshes with different underlying formats and mixing up which mesh you got a specific apf::MeshEntity from. 

If you retrieve an apf::MeshEntity from a mesh and need to cast it to the underlying type the assumption is you should understand explicitly what type of mesh you loaded. Design-wise though it would be preferable to build the functionality that requires casting apf::MeshEntity to some other type in such a way that it operates on apf::MeshEntitys instead.

Ultimately static_cast isn't going to prevent us from doing anything here, since apf::MeshEntity isn't really a well-defined type and we only ever allocate pointers to it, and casting a pointer-type to a pointer-type doesn't involve type-checking of the pointed-to type. Essentially we're using it similarly to a void*, we know that it is pointing to something, but don't really care what until it comes time to use it behind the API.

**Comment by cwsmith** [comment]
The following lines in MDS convert an APF mesh entity to an MDS entity using 
`reinterpret_cast`:

https://github.com/SCOREC/core/blob/bec4447ef0ec0b3f62d42272a5f29bedf2f3c99f/mds/apfMDS.cc#L76-L85

Likewise, in apfSim a `reinterpret_cast` is also used:

https://github.com/SCOREC/core/blob/bec4447ef0ec0b3f62d42272a5f29bedf2f3c99f/apf_sim/apfSIM.cc#L226-L239

Quoting SO: 
`reinterpret_cast` "...turns one type directly into another - such as casting
the value from one pointer to another, or storing a pointer in an int, or all
sorts of other nasty things. Largely, the only guarantee you get with
reinterpret_cast is that normally if you cast the result back to the original
type, you will get the exact same value (but not if the intermediate type is
smaller than the original type)."

This fits our use case since we simply want to expose/hide a native pointer 
from the apf 'MeshEntity' opaque pointer.

**Comment by cwsmith** [comment]
@yangf4 Please close the ticket if this answers your question.

**Comment by yangf4** [comment]
Thanks @tobinw  and @cwsmith 

This answers my question.
