### ISSUE TITLE
apply BC to mesh

### ISSUE THREAD

**Issue by cenxin995886** [SCOREC/core#155]
Whether PUMI could apply boundary conditions and material type to mesh?
Has anyone done anything like that？
Can someone give me some advice？Thank you!

**Comment by timetravellers** [comment]
Can you clarify your question a bit?

I think what most people do is define their model in Simmetrix simmodeler and read in the attributes from there.

As far as I know there is no equivalent way of dealing with boundary conditions in core, however you can store your boundary conditions and other material properties as tags or fields on your mesh. You may want to look at how it is done in https://github.com/SCOREC/core/blob/master/phasta/phAttrib.h and https://github.com/SCOREC/core/blob/master/phasta/phAttrib.cc

Note you need to be a bit careful if you are using the Simmetrix apis because you cannot open that code up unless the apis are already exposed in core, or you get permission from them to open whatever functions you need. @cwsmith may be able to shed more light on this aspect

**Comment by cenxin995886** [comment]
Sorry,my english is poor.But your answer help me a lot.Thank you firstly!

My plane for using PUMI is 1.useing gmodel and gmsh to build geometric model and get the initial mesh  2.using PUMI(meshadapt ,load balance partitioning) to refine the mesh. 3.apply or add boundary conditions and other material properties on mesh 4.get the mesh data for other finite element analysis program.

But I did not use Simmetrix. I use gmsh to build the geometric model and get the initial mesh.So whether I can do this like Simmetrix in core?

I think  I understand how to deal with boundary conditions and material properties maybe.
I could store  boundary conditions and other material properties as  tags or fields on the my initial mesh before refine mesh or after refine mesh?Than use finite element analysis program to explain those tags or fields.Is it right?

Is the method in https://github.com/SCOREC/core/blob/master/phasta/phAttrib.h and https://github.com/SCOREC/core/blob/master/phasta/phAttrib.cc only applicable to Sim？

**Comment by timetravellers** [comment]
As far as I know what you want to do is loop over the mesh entities which are classified on your geometric entity and set a field to the value of your boundary condition. You may also want to make sue of [apf::fix](https://www.scorec.rpi.edu/~seol/scorec/doxygen/namespaceapf.html#a46b2bad33dc710bf0713c236478d5696).

Although the implementation in phasta uses simmetrix you can look there to see how they read in information to the apf mesh.

**Comment by cenxin995886** [comment]
Yes!
What I want to do is what you said.
I'll have a good look at what you said
Thank you very much！
