### ISSUE TITLE
Compile error PRIu64 in phiotimer.cc at Phasta

### ISSUE THREAD

**Issue by eisungy** [SCOREC/core#157]
https://github.com/SCOREC/core/blob/9afeb19d855ce1e04239c113c094a8eee875a677/phasta/phiotimer.cc#L47

I'm compiling `core` in `Cori KNL` , and it shows an error at

```
/global/homes/e/eyoon/xgc_scorec_cori/core/phasta/phiotimer.cc(47): error: expected a ")"
      fprintf(stderr, "cycles %" PRIu64 " us %" PRIu64 " cycles per micro second %" PRIu64"\n", cycles, usec, cpus);
```

I'm using `CC` wrapping intel compiler. I tried `-std=c99` but it didn't help. No problem with others?

**Comment by cwsmith** [comment]
Develop and master have the fix for this.On Jul 23, 2018 6:20 AM, "E.S. Yoon" <notifications@github.com> wrote:https://github.com/SCOREC/core/blob/9afeb19d855ce1e04239c113c094a8eee875a677/phasta/phiotimer.cc#L47
I'm compiling core in Cori KNL , and it shows an error at
/global/homes/e/eyoon/xgc_scorec_cori/core/phasta/phiotimer.cc(47): error: expected a ")"
      fprintf(stderr, "cycles %" PRIu64 " us %" PRIu64 " cycles per micro second %" PRIu64"\n", cycles, usec, cpus);

I'm using CC wrapping intel compiler. I tried -std=c99 but it didn't help. No problem with others?

**Comment by eisungy** [comment]
Do you mean `master` branch? I cloned master 2 hours ago right before I created an issue.

**Comment by cwsmith** [comment]
Whoops.  Sorry about that.  It should be fixed now.

**Comment by eisungy** [comment]
@cwsmith Thank you so much! =)

**Comment by cwsmith** [comment]
You're welcome.
