### ISSUE TITLE
no libSimParasolid290.a any more for the lastest SimModSuite version 14.0-180803dev

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#167]
Instead, there is only `libSimParasolid300.a` for the lastest SimModSuite version 14.0-180803dev

We may need to upgrade the SimParasolid version here:
https://github.com/SCOREC/core/blob/master/cmake/FindSimModSuite.cmake#L99

But I am not sure if this change will break other compilations.

**Comment by KennethEJansen** [comment]
I made this change locally with version 12.0 and have not seen any problems.

That said, I have no idea what is going on with 13 and 14 so this comment only applies to 12.

---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by cwsmith** [comment]
develop/master use libSimParasolid290.a.  This is the newest version of the library common to the currently supported range of SimModSuite versions:

https://github.com/SCOREC/core/blob/4c4ba244022cce58d192de4834db2e9861fc924d/cmake/FindSimModSuite.cmake#L76-L77

Since SimModSuite 14.* is not released yet I don't want to change our max supported version and the version of `libSimParasolid`.  If there is no common libSimParasolid when SimModSuite 14 is released then we can create a map for SimModSuite-to-libSimParasolid versions.

$ find 11.0-170826/lib/. -name libSimParasolid\*
11.0-170826/lib/./x64_rhel7_gcc48/libSimParasolid290.a
11.0-170826/lib/./x64_rhel7_gcc48/libSimParasolid280.a

$ find 12.0-180713/ -name libSimParasolid\*
12.0-180713/lib/x64_rhel7_gcc48/libSimParasolid290.a
12.0-180713/lib/x64_rhel7_gcc48/libSimParasolid280.a
12.0-180713/lib/x64_rhel7_gcc48/libSimParasolid300.a

$ find 14.0-180803dev/ -name libSimParasolid\*
14.0-180803dev/lib/x64_rhel6_gcc44/libSimParasolid300.a

**Comment by cwsmith** [comment]
I'm going to close this under the assumption that the handful of folks who need the bleeding edge version of SimModSuite can adjust the version number in their builds.
