### ISSUE TITLE
Cannot make two "apf fields" with same name on two different simmetrix meshes

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#222]
Let us say I have already created an apf field "solution" on a simmetrix mesh "mesh_A" by using `createPackedField`, then it will fail if I try to create an apf field "solution" on another simmetrix mesh "mesh_B" by using `createPackedField`.

The reason for this is due to this line:
https://github.com/SCOREC/core/blob/81740e17d49c3377d02fccd00689b80479a5eb5a/apf_sim/apfSIM.cc#L543

`n` has to be unique. If `n` is already in use, an error results. Even though we are creating it for a different mesh. 

Any idea to resolve this issue? 

Note that if we create two "sim fields" with the same name on  two different simmetrix meshes by using `createSIMField`, it will be fine. 

In my opinion, `createPackedField` creates tag-like data attached on mesh but `createSIMField` creates field-like data on mesh.

**Comment by cwsmith** [comment]
I'm not very familiar with the fields interface so some of the following are notes on what I have just read.

As you said, `apf_sim/apfSIM.cc` implements the tag interface of `apf::Mesh` that supports the `createPackedField(...)` API.  
The `createSIMField(...)` family of functions depend on the Simmetrix FieldSim APIs (`SimField.h`) to [derive the `FieldDataOf<...>` class](https://github.com/SCOREC/core/blob/448b5f0548c8f9d63b6c499b65ef55c5e4bc034c/apf_sim/apfSIMDataOf.h#L11) which in turn is passed to [`makeField(...)`](https://github.com/SCOREC/core/blob/448b5f0548c8f9d63b6c499b65ef55c5e4bc034c/apf_sim/apfSIM.cc#L30-L31) ([definition](https://github.com/SCOREC/core/blob/448b5f0548c8f9d63b6c499b65ef55c5e4bc034c/apf/apfField.h#L73-L79), [implementation](https://github.com/SCOREC/core/blob/448b5f0548c8f9d63b6c499b65ef55c5e4bc034c/apf/apf.cc#L58-L81).

Conceptually, implementing the packed field as a single FieldSim or APF Field does not make sense since it is a set of different fields representing different physical quantities which cannot necessarily be operated on together (besides moving the data around with the associated mesh entities).

The only short term solution I see is to prepend or append a mesh specific identifier to the fields which are common among the multiple mesh instances.  I suppose we could implement this internally if tracking it on the user side was problematic/messy.

**Comment by yangf4** [comment]
`createPackedField` is at least used for phasta solution. To get rid of that, at [readAndAttachField(...)](https://github.com/SCOREC/core/blob/225b580907a35dbf86da890fbb5c47c35698304e/phasta/phRestart.cc#L331), we can split the data into three fields (pressure, velocity and temperature) and at [detachAndWriteField(...)](https://github.com/SCOREC/core/blob/225b580907a35dbf86da890fbb5c47c35698304e/phasta/phRestart.cc#L370), we can combine them into a data block. In this way, we can read/write the same data from/to phasta, we may not need to change the code of phasta. I think it is do-able. 

Certainly, I am not sure if `createPackedField` is also used by any other code/function.

**Comment by cwsmith** [comment]
IIRC, a few of the solution/error adaptation methods expect a packed solution field.  There are likely other functions that also expect the packed field.

If these are updated, and the restart file format is preserved, then I don't see a problem with this.

**Comment by cwsmith** [comment]
I'm going to close this issue. Please reopen if needed.
