### ISSUE TITLE
maSnap exceptions for 3D but not for 2D

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#313]
I have a question about the following line of code in [maSnap](https://github.com/SCOREC/core/blob/390452edabb8338cc18fccde25f4f64e5e2be81e/ma/maSnap.cc#L843). 

It purposely avoids considering snapping when a mesh vertex is classified on a model region in 3D. Why is this exception not extended to mesh vertices classified on the model region in 2D?

**Comment by cwsmith** [comment]
Hello,
Is the problematic case a 2D geometric model with a triangular mesh?  If so, why is there concern for classification on a model region (a volume)?

**Comment by zhang-alvin** [comment]
@cwsmith I was looking into creating a 2D analytic geometric model with a triangular mesh and I did not parameterize the model region. This led to an issue when calling MeshAdapt during the snapping procedure, which is avoided in 3D because of the indicated line. 

I have since created a geometric model with parameterizations for each entity, so I no longer have a problem, so this is more of a question.

**Comment by mortezah** [comment]
@zhang-alvin  It is kind of tricky to define the 2D problem. At best, things would be problem-dependent:

- On one hand, one can have a 2D domain on a flat surface, in which the boundary edges would be the equivalent of boundary faces in the 3D case and faces would be the equivalent of regions in the 3D case. For those cases, one can only snap things on the model edge and treat the model face as interior (like the regions in 3D) and snapping can be safely ignored. 
- On the other hand, one can have a 2D surface mesh that is actually classified on a curved model face (which is not necessarily flat). For that one, we would still want the snapping to happen for entities classified on the model face because the mesh has to conform to the model. 

The above description is an oversimplification of all the cases that can happen when dealing with 2D meshes. If you have a specific problem for which the condition (or lack of it for 2D) is causing a problem, I can take a look at it and think about adding some additional options to "ma::Input" when the mesh adapt is being set up, to handle those cases differently.

**Comment by zhang-alvin** [comment]
@mortezah I see. Thanks for the clarification. I didn't consider the second bullet. 

Again, no active issues that I'm having, but curious to know why that line of code was present.
