### ISSUE TITLE
expose getElementData for Fields

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#44]
we have a function `getElementNumbers` for `Numbering`s but no equivalent yet for `Field`s of various types. luckily this is supported just underneath by a generic function `apf::FieldDataOf<T>::getElementData`, so it should be straightforward to defined `getElementComponents` or something.

https://github.com/SCOREC/core/blob/master/apf/apfNumbering.cc#L187

**Comment by bgranzow** [comment]
These functions seem related to me:

https://github.com/SCOREC/core/blob/master/apf/apf.h#L439
https://github.com/SCOREC/core/blob/master/apf/apf.h#L443
https://github.com/SCOREC/core/blob/master/apf/apf.h#L447

Is the idea to make a single `getElementComponents ()` function that accepts any `FieldOf<T>`  type (SCALAR, VECTOR, MATRIX)? Is the idea to make a more convenient API for users so that they don't have to create apf::Elements to call a different API function?

I'm asking solely for my own curiosity.

**Comment by ibaned** [comment]
well I'll be darned. simply didn't look hard enough. those will do fine for the users I'm currently thinking of, though maybe `getElementComponents` would help later for packed fields etc.

**Comment by ibaned** [comment]
hold up... they're looking to get coordinates of element nodes... will the Vector variant do that ?

**Comment by ibaned** [comment]
I think yes...

**Comment by bgranzow** [comment]
I think you would have to create an `apf::Element` based on the `apf::Mesh::getCoordinateField()` shape, which seems redundant to me, but I think it should still work.
