### ISSUE TITLE
pumi_ment_getTopo missing implementation

### ISSUE THREAD

**Issue by timetravellers** [SCOREC/core#72]
No implementation was provided for `pumi_ment_getTopo`, however it appears in the header file, and in the pumi user guide.

**Comment by bgranzow** [comment]
@timetravellers I think [this](https://github.com/SCOREC/core/commit/57896d9207e87b5b6b2bdd0097e73fe5fa8a0521) commit should resolve this issue. It is currently in the develop branch and should make its way into the master branch around 5pm tonight.
@seegyoung Please verify that this implementation is correct.

**Comment by ibaned** [comment]
That has the same code as `pumi_ment_getType`, so one of them must be wrong. If I recall the confusing FMDB terminology, `Type` actually means dimensionality, while `Topo` indicates tetrahedron versus hexahedron, etc. In that case, I think separate from this issue, `pumi_ment_getType` is wrong, because in APF `Type` is the more precise one. There is `apf::getDimension(mesh, entity)` for getting the dimensionality of an entity.

**Comment by bgranzow** [comment]
Thanks @ibaned, I completely missed that other definition. The implementation of `pumi_ment_getTopo' is consistent with the  PUMI  [user's guide](https://www.scorec.rpi.edu/pumi/PUMI.pdf). `pumi_ment_getType' is not documented in the User's guide. In fact the only instance of `pumi_ment_getType' is in the source file pumi_mentity.cc, which leads me to believe it was supposed to be the implementation of `pumi_ment_getTopo', but was simply misspelled. Thus, I've deleted it [here](https://github.com/SCOREC/core/commit/a474ecc97687e2058c43e63098ae73a604261ed5).

**Comment by seegyoung** [comment]
I just found that I missed the implementation of pumi_ment_getTopo (misspelled to pumi_ment_getType in .cc).  Thanks for all the corrections. In PUMI, "type" and "dimension" are interchangeable.
