### ISSUE TITLE
Support 2nd order Coordinate Fields in zsplit 

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#78]
It looks like `zsplit` does not send the coordinates of higher order nodes from process 0 to the other processes.  For example 
![mesh_serial](https://cloud.githubusercontent.com/assets/10292902/23140571/5cfcafe6-f780-11e6-8bf7-d0a17a5e46b2.png)

becomes: 
![mesh_parallel](https://cloud.githubusercontent.com/assets/10292902/23140578/6871a53e-f780-11e6-8edd-3b133ef6d744.png)

Notice the gap between the two elements in rectangle (2, 3) from the bottom right corner

**Comment by mortezah** [comment]
@JaredCrean2 can you point me to the initial mesh? I assume this is a 2D mesh. Is that correct?

**Comment by seegyoung** [comment]
If you send me your test program, I will take a look.

**Comment by seegyoung** [comment]
I should have been more specific. Suppose you ran "zsplit" with mesh file "A". 
Please provide me the following if any
  - mesh file "A"
  - model file of "A" 
  - a program X that saved the mesh with the higher order nodes into the file "A"
  - any initial mesh file used to run the program "X"

**Comment by JaredCrean2** [comment]
If you have access to jumpgate, you can get the mesh and model files (before and after calling `zsplit`) in `tmp/curve_mre.tar.gz`.  

The code that created the mesh is [here](https://bitbucket.org/jcrean/createsmbmesh).  After building it, run `make_parallel_mesh2.sh 6 6 0 psquare 4` to recreate the mesh.  After running it, the `./meshfiles/` directory will have the files from before and after calling zsplit.

**Comment by seegyoung** [comment]
The "smb" file I/O doesn't support the higher order nodes so the initial mesh loaded from abc0.smb with "zsplit" didn't have the higher order nodes in the beginning. As we do not support the migration with higher order nodes either, my suggestion is to create an initial "partitioned" mesh without higher order nodes and create higher order nodes with the partitioned mesh later on.

**Comment by ibaned** [comment]
I'm pretty none of that is true, or at least it wasn't at some point. Both SMB files and migration should support "higher order nodes", because they are just tags on edges or faces etc. The SMB file IO should store the FieldShape name of all fields, including the coordinate field, and reload the mesh based on that knowledge. Maybe this got broken, but I'm pretty sure it used to work.

**Comment by ibaned** [comment]
@JaredCrean2  I think the problem is you're using a custom shape function (SBPShape). The auto-loading system only knows about shapes that were compiled with the program, so its probably ignoring your info because SBPShape isn't compiled in with zsplit. If you took the source code for zsplit and just recompiled it along with your SBPShape code in  a new executable, it should work. Another approach you should consider is to make your SBPShape part of the standard PUMI shapes.

**Comment by ibaned** [comment]
Here is the relevant code that should load shapes from file... unless you've compiled with `-DNDEBUG`, it should have aborted:

https://github.com/SCOREC/core/blob/master/apf/apfFile.cc#L104

**Comment by seegyoung** [comment]
@Dan, Thanks for looking at the issue. I agree - the issue is not being able to support the user-made field shape in file I/O.

**Comment by ibaned** [comment]
I think (as @JaredCrean2 did suggest), the problem is that `apf::packDataClone` and `apf::unpackDataClone` don't handle the coordinate field. The coordinate field is implicitly created when an empty mesh is made, and isn't listed by `apf::Mesh::countFields` and `apf::Mesh::getField`. Just augment these functions to send the name of the shape of the coordinate field, and change it if necessary at the destination:
https://github.com/SCOREC/core/blob/master/apf/apfMesh2.cc#L299
https://github.com/SCOREC/core/blob/master/apf/apfMesh2.cc#L305
Then things should work, at least for built-in shapes.

**Comment by seegyoung** [comment]
I should correct - the standard lagrange shape was used to generate the mesh.

**Comment by ibaned** [comment]
Excellent, that explains why SMB file I/O did manage to load it.

**Comment by ibaned** [comment]
I just pushed 7552d30 which just implements exactly what I said above. that should fix this issue. reopen if it doesn't.
